
name: Infrastructure

on:
  push:
    branches: [ master ]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'

jobs:
  infrastructure:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Prepare .env file
      shell: bash
      env:
        # Scaleway keys and project
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
        # UptimeRobot API Key
        UPTIMEROBOT_API_KEY: ${{ secrets.UPTIMEROBOT_API_KEY }}
        # OVH API
        OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
        OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
        OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
      run: |
        echo -e """# Scaleway keys and project
        export SCW_ACCESS_KEY="${SCW_ACCESS_KEY}"
        export SCW_SECRET_KEY="${SCW_SECRET_KEY}"
        export SCW_DEFAULT_PROJECT_ID="${SCW_DEFAULT_PROJECT_ID}"
        # UptimeRobot API Key
        export UPTIMEROBOT_API_KEY="${UPTIMEROBOT_API_KEY}"
        # OVH API
        export OVH_APPLICATION_KEY="${OVH_APPLICATION_KEY}"
        export OVH_APPLICATION_SECRET="${OVH_APPLICATION_SECRET}"
        export OVH_CONSUMER_KEY="${OVH_CONSUMER_KEY}"
        # TF API token
        export TF_API_TOKEN="${TF_API_TOKEN}"
        """ >> "./infrastructure/.env"

    - name: Prepare TF credentials file
      shell: bash
      env:
        # TF API token
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      run: |
        mkdir -p ./infrastructure/.terraform.d
        echo -e """{
          \"credentials\": {
            \"app.terraform.io\": {
              \"token\": \""${TF_API_TOKEN}"\"
            }
          }
        }
        """ >> "./infrastructure/.terraform.d/credentials.tfrc.json"
      

    # Runs a single command using the runners shell
    - name: Launch infrastructure creation
      shell: bash
      run: |
        source ./infrastructure/.env
        ./infrastructure/infrastructure.sh init
        ./infrastructure/infrastructure.sh plan
        ./infrastructure/infrastructure.sh apply
